--[[
    SimpleSpy Modern - Fixed Remote Spy v3
    Hook pattern migliorato per executor moderni
]]

if _G.SimpleSpyExecuted and type(_G.SimpleSpyShutdown) == "function" then
	pcall(_G.SimpleSpyShutdown)
end

local CoreGui = game:GetService("CoreGui")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")

-- Variables
local logs = {}
local blacklist = {}
local blocklist = {}
local layoutOrderNum = 999999999
local remoteLogs = {}
local sideClosed = true
local selected = nil
local remoteHooks = {}
local remoteSignals = {}

-- ScriptSignal
local function newSignal()
	local connected = {}
	return {
		Connect = function(self, f)
			connected[tostring(f)] = f
			return {Connected = true, Disconnect = function() connected[tostring(f)] = nil end}
		end,
		Fire = function(self, ...)
			for _, f in pairs(connected) do coroutine.wrap(f)(...) end
		end,
	}
end

-- Value to string
local function v2s(v)
	if typeof(v) == "number" then
		if v == math.huge then return "math.huge"
		elseif tostring(v):match("nan") then return "0/0 --[[NaN]]"
		else return tostring(v) end
	elseif typeof(v) == "boolean" then
		return tostring(v)
	elseif typeof(v) == "string" then
		return '"' .. string.gsub(v, '"', '\\"') .. '"'
	elseif typeof(v) == "Instance" then
		return v and ("game." .. v:GetFullName()) or "nil"
	elseif typeof(v) == "table" then
		local s = "{"
		for k, val in pairs(v) do s = s .. "\n    [" .. v2s(k) .. "] = " .. v2s(val) .. "," end
		return s .. "\n}"
	else
		return "nil --[[" .. typeof(v) .. "]]"
	end
end

local function genScript(remote, args)
	local gen = "-- Script generated by SimpleSpy\n\n"
	if #args > 0 then
		gen = gen .. "local args = {"
		for i, v in pairs(args) do gen = gen .. "\n    [" .. i .. "] = " .. v2s(v) .. "," end
		gen = gen .. "\n}\n\n"
		if remote:IsA("RemoteEvent") then
			gen = gen .. v2s(remote) .. ":FireServer(unpack(args))"
		elseif remote:IsA("RemoteFunction") then
			gen = gen .. v2s(remote) .. ":InvokeServer(unpack(args))"
		end
	else
		if remote:IsA("RemoteEvent") then
			gen = gen .. v2s(remote) .. ":FireServer()"
		elseif remote:IsA("RemoteFunction") then
			gen = gen .. v2s(remote) .. ":InvokeServer()"
		end
	end
	return gen
end

-- UI
local SimpleSpy2 = Instance.new("ScreenGui")
SimpleSpy2.Name = "SimpleSpy2"
SimpleSpy2.ResetOnSpawn = false
SimpleSpy2.Enabled = false

local Background = Instance.new("Frame")
Background.Name = "Background"
Background.Parent = SimpleSpy2
Background.BackgroundColor3 = Color3.fromRGB(30, 30, 35)
Background.BorderSizePixel = 0
Background.Position = UDim2.new(0, 500, 0, 200)
Background.Size = UDim2.new(0, 450, 0, 300)

local TopBar = Instance.new("Frame")
TopBar.Name = "TopBar"
TopBar.Parent = Background
TopBar.BackgroundColor3 = Color3.fromRGB(37, 35, 38)
TopBar.BorderSizePixel = 0
TopBar.Size = UDim2.new(0, 450, 0, 25)

local Title = Instance.new("TextLabel")
Title.Name = "Title"
Title.Parent = TopBar
Title.BackgroundTransparency = 1
Title.Position = UDim2.new(0, 10, 0, 0)
Title.Size = UDim2.new(0, 100, 0, 25)
Title.Font = Enum.Font.SourceSansBold
Title.Text = "SimpleSpy"
Title.TextColor3 = Color3.new(1, 1, 1)
Title.TextSize = 16
Title.TextXAlignment = Enum.TextXAlignment.Left

local CloseBtn = Instance.new("TextButton")
CloseBtn.Name = "CloseBtn"
CloseBtn.Parent = TopBar
CloseBtn.BackgroundColor3 = Color3.fromRGB(22, 22, 22)
CloseBtn.BorderSizePixel = 0
CloseBtn.Position = UDim2.new(1, -25, 0, 0)
CloseBtn.Size = UDim2.new(0, 25, 0, 25)
CloseBtn.Font = Enum.Font.SourceSans
CloseBtn.Text = "X"
CloseBtn.TextColor3 = Color3.new(1, 1, 1)
CloseBtn.TextSize = 14

local LeftPanel = Instance.new("Frame")
LeftPanel.Name = "LeftPanel"
LeftPanel.Parent = Background
LeftPanel.BackgroundColor3 = Color3.fromRGB(45, 44, 48)
LeftPanel.BorderSizePixel = 0
LeftPanel.Position = UDim2.new(0, 0, 0, 25)
LeftPanel.Size = UDim2.new(0, 150, 0, 275)

local LogList = Instance.new("ScrollingFrame")
LogList.Name = "LogList"
LogList.Parent = LeftPanel
LogList.Active = true
LogList.BackgroundTransparency = 1
LogList.BorderSizePixel = 0
LogList.Position = UDim2.new(0, 5, 0, 5)
LogList.Size = UDim2.new(0, 140, 0, 265)
LogList.CanvasSize = UDim2.new(0, 0, 2, 0)
LogList.ScrollBarThickness = 4

local UIListLayout = Instance.new("UIListLayout")
UIListLayout.Parent = LogList
UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
UIListLayout.Padding = UDim.new(0, 2)

local RightPanel = Instance.new("Frame")
RightPanel.Name = "RightPanel"
RightPanel.Parent = Background
RightPanel.BackgroundColor3 = Color3.fromRGB(35, 34, 38)
RightPanel.BorderSizePixel = 0
RightPanel.Position = UDim2.new(0, 150, 0, 25)
RightPanel.Size = UDim2.new(0, 300, 0, 275)

local CodeBox = Instance.new("TextBox")
CodeBox.Name = "CodeBox"
CodeBox.Parent = RightPanel
CodeBox.BackgroundColor3 = Color3.fromRGB(20, 20, 22)
CodeBox.BorderSizePixel = 0
CodeBox.Position = UDim2.new(0, 5, 0, 5)
CodeBox.Size = UDim2.new(0, 290, 0, 200)
CodeBox.Font = Enum.Font.Code
CodeBox.Text = "Seleziona un remote per vedere lo script..."
CodeBox.TextColor3 = Color3.new(1, 1, 1)
CodeBox.TextSize = 14
CodeBox.TextXAlignment = Enum.TextXAlignment.Left
CodeBox.TextYAlignment = Enum.TextYAlignment.Top
CodeBox.ClearTextOnFocus = false
CodeBox.MultiLine = true

local CopyBtn = Instance.new("TextButton")
CopyBtn.Name = "CopyBtn"
CopyBtn.Parent = RightPanel
CopyBtn.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
CopyBtn.BorderSizePixel = 0
CopyBtn.Position = UDim2.new(0, 5, 0, 210)
CopyBtn.Size = UDim2.new(0, 100, 0, 25)
CopyBtn.Font = Enum.Font.SourceSans
CopyBtn.Text = "Copy"
CopyBtn.TextColor3 = Color3.new(1, 1, 1)
CopyBtn.TextSize = 14

local RunBtn = Instance.new("TextButton")
RunBtn.Name = "RunBtn"
RunBtn.Parent = RightPanel
RunBtn.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
RunBtn.BorderSizePixel = 0
RunBtn.Position = UDim2.new(0, 110, 0, 210)
RunBtn.Size = UDim2.new(0, 100, 0, 25)
RunBtn.Font = Enum.Font.SourceSans
RunBtn.Text = "Run"
RunBtn.TextColor3 = Color3.new(1, 1, 1)
RunBtn.TextSize = 14

-- Template
local Template = Instance.new("TextButton")
Template.Name = "Template"
Template.Parent = LogList
Template.BackgroundColor3 = Color3.fromRGB(50, 50, 55)
Template.BorderSizePixel = 0
Template.Size = UDim2.new(1, 0, 0, 25)
Template.Font = Enum.Font.SourceSans
Template.Text = ""
Template.TextColor3 = Color3.new(1, 1, 1)
Template.TextSize = 14
Template.AutoButtonColor = false
Template.Visible = false

local TemplateBar = Instance.new("Frame")
TemplateBar.Name = "TemplateBar"
TemplateBar.Parent = Template
TemplateBar.BackgroundColor3 = Color3.fromRGB(255, 242, 0)
TemplateBar.BorderSizePixel = 0
TemplateBar.Position = UDim2.new(0, 0, 0, 4)
TemplateBar.Size = UDim2.new(0, 5, 0, 17)

-- Logging function
local function addRemote(type, name, args, remote, blocked)
	if blacklist[remote] or blacklist[name] then return end
	
	local entry = Template:Clone()
	entry.Text = string.sub(name, 1, 40)
	entry.Visible = true
	entry.Name = name .. "_" .. tick()
	entry.LayoutOrder = layoutOrderNum
	layoutOrderNum = layoutOrderNum - 1
	
	local log = {
		Name = name,
		Remote = remote,
		Args = args,
		Blocked = blocked,
		GenScript = blocked and "-- REMOTE BLOCKED\n\n" .. genScript(remote, args) or genScript(remote, args),
	}
	
	logs[#logs + 1] = log
	
	entry.MouseButton1Click:Connect(function()
		if selected then
			TweenService:Create(selected.Button, TweenInfo.new(0.2), {BackgroundColor3 = Color3.fromRGB(50, 50, 55)}):Play()
		end
		selected = log
		log.Button = entry
		TweenService:Create(entry, TweenInfo.new(0.2), {BackgroundColor3 = Color3.fromRGB(92, 126, 229)}):Play()
		CodeBox.Text = log.GenScript
		if sideClosed then
			sideClosed = false
			TweenService:Create(RightPanel, TweenInfo.new(0.3), {Size = UDim2.new(0, 300, 0, 275)}):Play()
		end
	end)
	
	entry.Parent = LogList
	table.insert(remoteLogs, entry)
	
	LogList.CanvasSize = UDim2.new(0, 0, 0, UIListLayout.AbsoluteContentSize.Y)
end

-- Hook setup
local oldNamecall

local function setupHooks()
	local succ, err = pcall(function()
		if not hookmetamethod or not getnamecallmethod then
			error("hookmetamethod/getnamecallmethod non disponibili")
		end
		
		-- IMPORTANT: Store old namecall in upvalue, NOT local variable
		oldNamecall = hookmetamethod(game, "__namecall", function(self, ...)
			local method = getnamecallmethod()
			local args = {...}
			
			if typeof(self) == "Instance" and (method == "FireServer" or method == "InvokeServer") then
				local name = self.Name
				
				-- Fire signal
				if remoteSignals[self] then
					remoteSignals[self]:Fire(method, args)
				end
				
				-- Apply hooks
				if remoteHooks[self] then
					args = remoteHooks[self](unpack(args))
					if not args then args = {} end
				end
				
				-- Check blocklist
				if blocklist[self] or blocklist[name] then
					spawn(function() addRemote(method == "FireServer" and "event" or "function", name, args, self, true) end)
					return
				end
				
				-- Log remote
				spawn(function() addRemote(method == "FireServer" and "event" or "function", name, args, self, false) end)
			end
			
			-- CRITICAL: Must call the stored oldNamecall function
			return oldNamecall(self, ...)
		end)
	end)
	
	return succ, err
end

-- API
local SimpleSpy = {}

function SimpleSpy:GetRemoteFiredSignal(remote)
	assert(typeof(remote) == "Instance", "Instance expected, got " .. typeof(remote))
	remoteSignals[remote] = remoteSignals[remote] or newSignal()
	return remoteSignals[remote]
end

function SimpleSpy:HookRemote(remote, callback)
	assert(typeof(remote) == "Instance", "Instance expected")
	assert(typeof(callback) == "function", "function expected")
	remoteHooks[remote] = callback
end

function SimpleSpy:BlockRemote(remote)
	assert(typeof(remote) == "Instance" or typeof(remote) == "string", "Instance or string expected")
	blocklist[remote] = true
end

function SimpleSpy:ExcludeRemote(remote)
	assert(typeof(remote) == "Instance" or typeof(remote) == "string", "Instance or string expected")
	blacklist[remote] = true
end

function SimpleSpy:ValueToString(value) return v2s(value) end
function SimpleSpy:TableToVars(t) return v2s(t) end
function SimpleSpy:ArgsToString(method, args) return v2s({args = args}) .. "\n\n" .. method .. "(unpack(args))" end

-- UI Events
CloseBtn.MouseButton1Click:Connect(function()
	SimpleSpy2:Destroy()
	_G.SimpleSpyExecuted = nil
	if oldNamecall then hookmetamethod(game, "__namecall", oldNamecall) end
end)

CopyBtn.MouseButton1Click:Connect(function()
	if selected and selected.GenScript then
		if setclipboard then setclipboard(selected.GenScript) end
		CopyBtn.Text = "Copied!"
		delay(1, function() CopyBtn.Text = "Copy" end)
	end
end)

RunBtn.MouseButton1Click:Connect(function()
	if selected and selected.GenScript then
		local ok, err = pcall(function()
			loadstring(selected.GenScript)()
		end)
		RunBtn.Text = ok and "Success!" or "Error!"
		delay(1, function() RunBtn.Text = "Run" end)
	end
end)

Title.MouseButton1Click:Connect(function()
	sideClosed = not sideClosed
	if sideClosed then
		TweenService:Create(RightPanel, TweenInfo.new(0.3), {Size = UDim2.new(0, 0, 0, 275)}):Play()
	else
		TweenService:Create(RightPanel, TweenInfo.new(0.3), {Size = UDim2.new(0, 300, 0, 275)}):Play()
	end
end)

-- Initialize
if RunService:IsClient() then
	local succ, err = setupHooks()
	if not succ then
		warn("SimpleSpy hook failed:", err)
	else
		_G.SimpleSpyExecuted = true
		_G.SimpleSpyShutdown = function()
			_G.SimpleSpyExecuted = nil
			SimpleSpy2:Destroy()
			if oldNamecall then hookmetamethod(game, "__namecall", oldNamecall) end
		end
		
		if gethui then SimpleSpy2.Parent = gethui() else SimpleSpy2.Parent = CoreGui end
		SimpleSpy2.Enabled = true
		Template.Parent = nil
		
		print("SimpleSpy Modern inizializzato!")
	end
else
	error("SimpleSpy solo per client!")
end

return SimpleSpy