--[[
    SimpleSpy Modern - Fixed Remote Spy v4
    Con supporto multi-executor e debug
]]

if _G.SimpleSpyExecuted and type(_G.SimpleSpyShutdown) == "function" then
	pcall(_G.SimpleSpyShutdown)
end

local CoreGui = game:GetService("CoreGui")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")

-- Variables
local logs = {}
local blacklist = {}
local blocklist = {}
local layoutOrderNum = 999999999
local remoteLogs = {}
local sideClosed = true
local selected = nil
local remoteHooks = {}
local remoteSignals = {}
local hookSuccess = false

-- ScriptSignal
local function newSignal()
	local connected = {}
	return {
		Connect = function(self, f)
			connected[tostring(f)] = f
			return {Connected = true, Disconnect = function() connected[tostring(f)] = nil end}
		end,
		Fire = function(self, ...)
			for _, f in pairs(connected) do coroutine.wrap(f)(...) end
		end,
	}
end

-- Value to string
local function v2s(v)
	if typeof(v) == "number" then
		if v == math.huge then return "math.huge"
		elseif tostring(v):match("nan") then return "0/0 --[[NaN]]"
		else return tostring(v) end
	elseif typeof(v) == "boolean" then return tostring(v)
	elseif typeof(v) == "string" then return '"' .. string.gsub(v, '"', '\\"') .. '"'
	elseif typeof(v) == "Instance" then return v and ("game." .. v:GetFullName()) or "nil"
	elseif typeof(v) == "table" then
		local s = "{"
		for k, val in pairs(v) do s = s .. "\n    [" .. v2s(k) .. "] = " .. v2s(val) .. "," end
		return s .. "\n}"
	else return "nil --[[" .. typeof(v) .. "]]" end
end

local function genScript(remote, args)
	local gen = "-- Script generated by SimpleSpy\n\n"
	if #args > 0 then
		gen = gen .. "local args = {"
		for i, v in pairs(args) do gen = gen .. "\n    [" .. i .. "] = " .. v2s(v) .. "," end
		gen = gen .. "\n}\n\n"
		if remote:IsA("RemoteEvent") then
			gen = gen .. v2s(remote) .. ":FireServer(unpack(args))"
		elseif remote:IsA("RemoteFunction") then
			gen = gen .. v2s(remote) .. ":InvokeServer(unpack(args))"
		end
	else
		if remote:IsA("RemoteEvent") then gen = gen .. v2s(remote) .. ":FireServer()"
		elseif remote:IsA("RemoteFunction") then gen = gen .. v2s(remote) .. ":InvokeServer()" end
	end
	return gen
end

-- UI
local SimpleSpy2 = Instance.new("ScreenGui")
SimpleSpy2.Name = "SimpleSpy2"
SimpleSpy2.ResetOnSpawn = false

local Background = Instance.new("Frame")
Background.Name = "Background"
Background.Parent = SimpleSpy2
Background.BackgroundColor3 = Color3.fromRGB(30, 30, 35)
Background.BorderSizePixel = 0
Background.Position = UDim2.new(0, 500, 0, 200)
Background.Size = UDim2.new(0, 450, 0, 300)

local TopBar = Instance.new("Frame")
TopBar.Name = "TopBar"
TopBar.Parent = Background
TopBar.BackgroundColor3 = Color3.fromRGB(37, 35, 38)
TopBar.BorderSizePixel = 0
TopBar.Size = UDim2.new(0, 450, 0, 25)

local Title = Instance.new("TextButton")
Title.Name = "Title"
Title.Parent = TopBar
Title.BackgroundTransparency = 1
Title.Position = UDim2.new(0, 10, 0, 0)
Title.Size = UDim2.new(0, 100, 0, 25)
Title.Font = Enum.Font.SourceSansBold
Title.Text = "SimpleSpy"
Title.TextColor3 = Color3.new(1, 1, 1)
Title.TextSize = 16
Title.AutoButtonColor = false

local CloseBtn = Instance.new("TextButton")
CloseBtn.Name = "CloseBtn"
CloseBtn.Parent = TopBar
CloseBtn.BackgroundColor3 = Color3.fromRGB(22, 22, 22)
CloseBtn.BorderSizePixel = 0
CloseBtn.Position = UDim2.new(1, -25, 0, 0)
CloseBtn.Size = UDim2.new(0, 25, 0, 25)
CloseBtn.Font = Enum.Font.SourceSans
CloseBtn.Text = "X"
CloseBtn.TextColor3 = Color3.new(1, 1, 1)
CloseBtn.TextSize = 14

local LeftPanel = Instance.new("Frame")
LeftPanel.Name = "LeftPanel"
LeftPanel.Parent = Background
LeftPanel.BackgroundColor3 = Color3.fromRGB(45, 44, 48)
LeftPanel.BorderSizePixel = 0
LeftPanel.Position = UDim2.new(0, 0, 0, 25)
LeftPanel.Size = UDim2.new(0, 150, 0, 275)

local LogList = Instance.new("ScrollingFrame")
LogList.Name = "LogList"
LogList.Parent = LeftPanel
LogList.Active = true
LogList.BackgroundTransparency = 1
LogList.BorderSizePixel = 0
LogList.Position = UDim2.new(0, 5, 0, 5)
LogList.Size = UDim2.new(0, 140, 0, 265)
LogList.CanvasSize = UDim2.new(0, 0, 0, 0)
LogList.ScrollBarThickness = 4

local UIListLayout = Instance.new("UIListLayout")
UIListLayout.Parent = LogList
UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
UIListLayout.Padding = UDim.new(0, 2)

local RightPanel = Instance.new("Frame")
RightPanel.Name = "RightPanel"
RightPanel.Parent = Background
RightPanel.BackgroundColor3 = Color3.fromRGB(35, 34, 38)
RightPanel.BorderSizePixel = 0
RightPanel.Position = UDim2.new(0, 150, 0, 25)
RightPanel.Size = UDim2.new(0, 300, 0, 275)

local CodeBox = Instance.new("TextBox")
CodeBox.Name = "CodeBox"
CodeBox.Parent = RightPanel
CodeBox.BackgroundColor3 = Color3.fromRGB(20, 20, 22)
CodeBox.BorderSizePixel = 0
CodeBox.Position = UDim2.new(0, 5, 0, 5)
CodeBox.Size = UDim2.new(0, 290, 0, 200)
CodeBox.Font = Enum.Font.Code
CodeBox.Text = "Inizializzazione..."
CodeBox.TextColor3 = Color3.new(1, 1, 1)
CodeBox.TextSize = 14
CodeBox.TextXAlignment = Enum.TextXAlignment.Left
CodeBox.TextYAlignment = Enum.TextYAlignment.Top
CodeBox.ClearTextOnFocus = false
CodeBox.MultiLine = true

local CopyBtn = Instance.new("TextButton")
CopyBtn.Name = "CopyBtn"
CopyBtn.Parent = RightPanel
CopyBtn.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
CopyBtn.BorderSizePixel = 0
CopyBtn.Position = UDim2.new(0, 5, 0, 210)
CopyBtn.Size = UDim2.new(0, 100, 0, 25)
CopyBtn.Font = Enum.Font.SourceSans
CopyBtn.Text = "Copy Script"
CopyBtn.TextColor3 = Color3.new(1, 1, 1)
CopyBtn.TextSize = 14

local RunBtn = Instance.new("TextButton")
RunBtn.Name = "RunBtn"
RunBtn.Parent = RightPanel
RunBtn.BackgroundColor3 = Color3.fromRGB(70, 70, 70)
RunBtn.BorderSizePixel = 0
RunBtn.Position = UDim2.new(0, 110, 0, 210)
RunBtn.Size = UDim2.new(0, 100, 0, 25)
RunBtn.Font = Enum.Font.SourceSans
RunBtn.Text = "Execute"
RunBtn.TextColor3 = Color3.new(1, 1, 1)
RunBtn.TextSize = 14

local StatusLabel = Instance.new("TextLabel")
StatusLabel.Name = "StatusLabel"
StatusLabel.Parent = RightPanel
StatusLabel.BackgroundTransparency = 1
StatusLabel.Position = UDim2.new(0, 5, 0, 238)
StatusLabel.Size = UDim2.new(0, 290, 0, 20)
StatusLabel.Font = Enum.Font.SourceSans
StatusLabel.Text = "Pronto - In attesa di remote..."
StatusLabel.TextColor3 = Color3.fromRGB(200, 200, 200)
StatusLabel.TextSize = 12
StatusLabel.TextXAlignment = Enum.TextXAlignment.Left

-- Template
local Template = Instance.new("TextButton")
Template.Name = "Template"
Template.Parent = LogList
Template.BackgroundColor3 = Color3.fromRGB(80, 80, 85)
Template.BorderSizePixel = 0
Template.Size = UDim2.new(1, 0, 0, 25)
Template.Font = Enum.Font.SourceSans
Template.Text = ""
Template.TextColor3 = Color3.new(1, 1, 1)
Template.TextSize = 14
Template.AutoButtonColor = false
Template.Visible = false

local TemplateBar = Instance.new("Frame")
TemplateBar.Name = "TemplateBar"
TemplateBar.Parent = Template
TemplateBar.BackgroundColor3 = Color3.fromRGB(255, 242, 0)
TemplateBar.BorderSizePixel = 0
TemplateBar.Position = UDim2.new(0, 0, 0, 4)
TemplateBar.Size = UDim2.new(0, 5, 0, 17)

local TemplateText = Instance.new("TextLabel")
TemplateText.Name = "TemplateText"
TemplateText.Parent = Template
TemplateText.BackgroundTransparency = 1
TemplateText.Position = UDim2.new(0, 8, 0, 0)
TemplateText.Size = UDim2.new(1, -8, 1, 0)
TemplateText.Font = Enum.Font.SourceSans
TemplateText.Text = "RemoteName"
TemplateText.TextColor3 = Color3.new(1, 1, 1)
TemplateText.TextSize = 14
TemplateText.TextXAlignment = Enum.TextXAlignment.Left

-- Logging function
local function addRemote(type, name, args, remote, blocked)
	if blacklist[remote] or blacklist[name] then return end
	
	local entry = Template:Clone()
	entry.Visible = true
	entry.Name = name .. "_" .. tick()
	entry.LayoutOrder = layoutOrderNum
	layoutOrderNum = layoutOrderNum - 1
	
	local log = {
		Name = name,
		Remote = remote,
		Args = args,
		Blocked = blocked,
		GenScript = blocked and "-- REMOTE BLOCKED\n\n" .. genScript(remote, args) or genScript(remote, args),
	}
	
	logs[#logs + 1] = log
	
	entry.MouseButton1Click:Connect(function()
		if selected then
			TweenService:Create(selected.Frame, TweenInfo.new(0.2), {BackgroundColor3 = Color3.fromRGB(80, 80, 85)}):Play()
		end
		selected = log
		log.Frame = entry
		TweenService:Create(entry, TweenInfo.new(0.2), {BackgroundColor3 = Color3.fromRGB(92, 126, 229)}):Play()
		CodeBox.Text = log.GenScript
		StatusLabel.Text = "Remote: " .. name
		if sideClosed then
			sideClosed = false
			RightPanel.Size = UDim2.new(0, 300, 0, 275)
		end
	end)
	
	entry.Parent = LogList
	table.insert(remoteLogs, entry)
	
	LogList.CanvasSize = UDim2.new(0, 0, 0, UIListLayout.AbsoluteContentSize.Y + 10)
	TemplateText.Text = string.sub(name, 1, 40)
end

-- Setup hooks
local function setupHooks()
	-- Try hookmetamethod first (Synapse X, Krampus, etc)
	if hookmetamethod and getnamecallmethod then
		local old = hookmetamethod(game, "__namecall", function(self, ...)
			local method = getnamecallmethod()
			local args = {...}
			
			if typeof(self) == "Instance" and (method == "FireServer" or method == "InvokeServer") then
				local name = self.Name
				
				-- Fire signal
				if remoteSignals[self] then
					remoteSignals[self]:Fire(method, args)
				end
				
				-- Apply hooks
				if remoteHooks[self] then
					args = remoteHooks[self](unpack(args))
					if not args then args = {} end
				end
				
				-- Check blocklist
				if blocklist[self] or blocklist[name] then
					spawn(function() addRemote(method == "FireServer" and "event" or "function", name, args, self, true) end)
					return nil
				end
				
				-- Log remote
				spawn(function() addRemote(method == "FireServer" and "event" or "function", name, args, self, false) end)
			end
			
			return old(self, ...)
		end)
		
		if old then
			hookSuccess = true
			_G.SimpleSpyHookBackup = old
			return true
		end
	end
	
	-- Fallback to getrawmetatable (deprecated executors)
	if getrawmetatable and setreadonly then
		local mt = getrawmetatable(game)
		if mt and mt.__namecall then
			_G.SimpleSpyOriginalNamecall = mt.__namecall
			setreadonly(mt, false)
			mt.__namecall = function(self, ...)
				local method = getnamecallmethod and getnamecallmethod() or ""
				local args = {...}
				
				if typeof(self) == "Instance" and (method == "FireServer" or method == "InvokeServer") then
					local name = self.Name
					
					if remoteSignals[self] then
						remoteSignals[self]:Fire(method, args)
					end
					
					if remoteHooks[self] then
						args = remoteHooks[self](unpack(args))
						if not args then args = {} end
					end
					
					if blocklist[self] or blocklist[name] then
						spawn(function() addRemote(method == "FireServer" and "event" or "function", name, args, self, true) end)
						return nil
					end
					
					spawn(function() addRemote(method == "FireServer" and "event" or "function", name, args, self, false) end)
				end
				
				return _G.SimpleSpyOriginalNamecall(self, ...)
			end
			setreadonly(mt, true)
			hookSuccess = true
			return true
		end
	end
	
	return false
end

-- API
local SimpleSpy = {}

function SimpleSpy:GetRemoteFiredSignal(remote)
	assert(typeof(remote) == "Instance", "Instance expected, got " .. typeof(remote))
	remoteSignals[remote] = remoteSignals[remote] or newSignal()
	return remoteSignals[remote]
end

function SimpleSpy:HookRemote(remote, callback)
	assert(typeof(remote) == "Instance", "Instance expected")
	assert(typeof(callback) == "function", "function expected")
	remoteHooks[remote] = callback
end

function SimpleSpy:BlockRemote(remote)
	assert(typeof(remote) == "Instance" or typeof(remote) == "string", "Instance or string expected")
	blocklist[remote] = true
end

function SimpleSpy:ExcludeRemote(remote)
	assert(typeof(remote) == "Instance" or typeof(remote) == "string", "Instance or string expected")
	blacklist[remote] = true
end

function SimpleSpy:ValueToString(value) return v2s(value) end
function SimpleSpy:TableToVars(t) return v2s(t) end
function SimpleSpy:ArgsToString(method, args) return v2s({args = args}) .. "\n\n" .. method .. "(unpack(args))" end

-- UI Events
CloseBtn.MouseButton1Click:Connect(function()
	SimpleSpy2:Destroy()
	_G.SimpleSpyExecuted = nil
	_G.SimpleSpyShutdown = nil
	if _G.SimpleSpyHookBackup then
		hookmetamethod(game, "__namecall", _G.SimpleSpyHookBackup)
	end
	if _G.SimpleSpyOriginalNamecall then
		local mt = getrawmetatable(game)
		if mt then setreadonly(mt, false) mt.__namecall = _G.SimpleSpyOriginalNamecall setreadonly(mt, true) end
	end
end)

CopyBtn.MouseButton1Click:Connect(function()
	if selected and selected.GenScript then
		if setclipboard then
			setclipboard(selected.GenScript)
			CopyBtn.Text = "Copied!"
			delay(1, function() CopyBtn.Text = "Copy Script" end)
		end
	end
end)

RunBtn.MouseButton1Click:Connect(function()
	if selected and selected.GenScript then
		local ok, err = pcall(function() loadstring(selected.GenScript)() end)
		RunBtn.Text = ok and "Success!" or "Error!"
		delay(1, function() RunBtn.Text = "Execute" end)
	end
end)

Title.MouseButton1Click:Connect(function()
	sideClosed = not sideClosed
	if sideClosed then
		RightPanel.Size = UDim2.new(0, 0, 0, 275)
	else
		RightPanel.Size = UDim2.new(0, 300, 0, 275)
	end
end)

-- Initialize
if RunService:IsClient() then
	_G.SimpleSpyExecuted = true
	_G.SimpleSpyShutdown = function()
		_G.SimpleSpyExecuted = nil
		if _G.SimpleSpyHookBackup then
			hookmetamethod(game, "__namecall", _G.SimpleSpyHookBackup)
		end
		SimpleSpy2:Destroy()
	end
	
	if gethui then SimpleSpy2.Parent = gethui() else SimpleSpy2.Parent = CoreGui end
	Template.Parent = nil
	
	if setupHooks() then
		CodeBox.Text = "-- SimpleSpy Modern v2 - Hook attivo!\n-- Clicca sui remote per vedere lo script"
		StatusLabel.Text = "Hook attivo - Monitora RemoteEvent e RemoteFunction"
		print("SimpleSpy Modern inizializzato!")
	else
		CodeBox.Text = "-- ERROR: Hook non supportato!\n-- L'executor non ha hookmetamethod/getrawmetatable"
		StatusLabel.Text = "Hook FALLITO - Executor non supportato"
		warn("SimpleSpy: Nessun metodo di hook disponibile!")
	end
else
	error("SimpleSpy solo per client!")
end

return SimpleSpy