--[[
    SimpleSpy Modern - Reworked Remote Spy with updated hooking method
    Uses hookmetamethod which works in modern executors (Synapse X, Krampus, etc.)
]]

if _G.SimpleSpyExecuted and type(_G.SimpleSpyShutdown) == "function" then
	pcall(_G.SimpleSpyShutdown)
end

local Players = game:GetService("Players")
local CoreGui = game:GetService("CoreGui")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")

-- RemoteSpy Variables
local logs = {}
local blacklist = {}
local blocklist = {}
local layoutOrderNum = 999999999
local remoteLogs = {}
local sideClosed = true
local selected = nil
local remoteHooks = {}

-- ScriptSignal implementation
local function newSignal()
	local connected = {}
	return {
		Connect = function(self, f)
			connected[tostring(f)] = f
			return {
				Connected = true,
				Disconnect = function()
					connected[tostring(f)] = nil
				end,
			}
		end,
		Fire = function(self, ...)
			for _, f in pairs(connected) do
				coroutine.wrap(f)(...)
			end
		end,
	}
end

local remoteSignals = {}

-- Value to string conversion
local function formatstr(str)
	return '"' .. string.gsub(str, '"', '\\226\\128\\162') .. '"'
end

local function v2s(v)
	if typeof(v) == "number" then
		if v == math.huge then return "math.huge"
		elseif tostring(v):match("nan") then return "0/0 --[[NaN]]"
		else return tostring(v) end
	elseif typeof(v) == "boolean" then
		return tostring(v)
	elseif typeof(v) == "string" then
		return formatstr(v)
	elseif typeof(v) == "Instance" then
		if v == nil then return "nil" end
		return "game." .. v:GetFullName()
	elseif typeof(v) == "table" then
		local s = "{"
		for k, val in pairs(v) do
			s = s .. "\n    [" .. v2s(k) .. "] = " .. v2s(val) .. ","
		end
		return s .. "\n}"
	else
		return "nil --[[" .. typeof(v) .. "]]"
	end
end

local function genScript(remote, args)
	local gen = "-- Script generated by SimpleSpy\n\n"
	if #args > 0 then
		gen = gen .. "local args = {"
		for i, v in pairs(args) do
			gen = gen .. "\n    [" .. i .. "] = " .. v2s(v) .. ","
		end
		gen = gen .. "\n}\n\n"
		if remote:IsA("RemoteEvent") then
			gen = gen .. v2s(remote) .. ":FireServer(unpack(args))"
		elseif remote:IsA("RemoteFunction") then
			gen = gen .. v2s(remote) .. ":InvokeServer(unpack(args))"
		end
	else
		if remote:IsA("RemoteEvent") then
			gen = gen .. v2s(remote) .. ":FireServer()"
		elseif remote:IsA("RemoteFunction") then
			gen = gen .. v2s(remote) .. ":InvokeServer()"
		end
	end
	return gen
end

-- UI Creation
local SimpleSpy2 = Instance.new("ScreenGui")
SimpleSpy2.Name = "SimpleSpy2"
SimpleSpy2.ResetOnSpawn = false

local Background = Instance.new("Frame")
Background.Name = "Background"
Background.Parent = SimpleSpy2
Background.BackgroundColor3 = Color3.new(1, 1, 1)
Background.BackgroundTransparency = 1
Background.Position = UDim2.new(0, 500, 0, 200)
Background.Size = UDim2.new(0, 450, 0, 268)

local LeftPanel = Instance.new("Frame")
LeftPanel.Name = "LeftPanel"
LeftPanel.Parent = Background
LeftPanel.BackgroundColor3 = Color3.fromRGB(53, 52, 55)
LeftPanel.BorderSizePixel = 0
LeftPanel.Position = UDim2.new(0, 0, 0, 19)
LeftPanel.Size = UDim2.new(0, 131, 0, 249)

local TopBar = Instance.new("Frame")
TopBar.Name = "TopBar"
TopBar.Parent = Background
TopBar.BackgroundColor3 = Color3.fromRGB(37, 35, 38)
TopBar.BorderSizePixel = 0
TopBar.Size = UDim2.new(0, 450, 0, 19)

local Simple = Instance.new("TextButton")
Simple.Name = "Simple"
Simple.Parent = TopBar
Simple.BackgroundTransparency = 1
Simple.AutoButtonColor = false
Simple.Position = UDim2.new(0, 5, 0, 0)
Simple.Size = UDim2.new(0, 57, 0, 18)
Simple.Font = Enum.Font.SourceSansBold
Simple.Text = "SimpleSpy"
Simple.TextColor3 = Color3.new(1, 1, 1)
Simple.TextSize = 14
Simple.TextXAlignment = Enum.TextXAlignment.Left

local CloseButton = Instance.new("TextButton")
CloseButton.Name = "CloseButton"
CloseButton.Parent = TopBar
CloseButton.BackgroundColor3 = Color3.fromRGB(22, 22, 22)
CloseButton.BorderSizePixel = 0
CloseButton.Position = UDim2.new(1, -19, 0, 0)
CloseButton.Size = UDim2.new(0, 19, 0, 19)
CloseButton.Font = Enum.Font.SourceSans
CloseButton.Text = "X"
CloseButton.TextColor3 = Color3.new(1, 1, 1)
CloseButton.TextSize = 14

local LogList = Instance.new("ScrollingFrame")
LogList.Name = "LogList"
LogList.Parent = LeftPanel
LogList.Active = true
LogList.BackgroundTransparency = 1
LogList.BorderSizePixel = 0
LogList.Position = UDim2.new(0, 0, 0, 9)
LogList.Size = UDim2.new(0, 131, 0, 232)
LogList.CanvasSize = UDim2.new(0, 0, 0, 0)
LogList.ScrollBarThickness = 4

local UIListLayout = Instance.new("UIListLayout")
UIListLayout.Parent = LogList
UIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center
UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder

local RemoteTemplate = Instance.new("Frame")
RemoteTemplate.Name = "RemoteTemplate"
RemoteTemplate.Parent = LogList
RemoteTemplate.BackgroundTransparency = 1
RemoteTemplate.Size = UDim2.new(0, 117, 0, 27)

local ColorBar = Instance.new("Frame")
ColorBar.Name = "ColorBar"
ColorBar.Parent = RemoteTemplate
ColorBar.BackgroundColor3 = Color3.fromRGB(255, 242, 0)
ColorBar.BorderSizePixel = 0
ColorBar.Position = UDim2.new(0, 0, 0, 1)
ColorBar.Size = UDim2.new(0, 7, 0, 18)
ColorBar.ZIndex = 2

local Text = Instance.new("TextLabel")
Text.Name = "Text"
Text.Parent = RemoteTemplate
Text.BackgroundTransparency = 1
Text.Position = UDim2.new(0, 12, 0, 1)
Text.Size = UDim2.new(0, 105, 0, 18)
Text.ZIndex = 2
Text.Font = Enum.Font.SourceSans
Text.Text = "TEXT"
Text.TextColor3 = Color3.new(1, 1, 1)
Text.TextSize = 14
Text.TextXAlignment = Enum.TextXAlignment.Left
Text.TextWrapped = true

local Button = Instance.new("TextButton")
Button.Name = "Button"
Button.Parent = RemoteTemplate
Button.BackgroundColor3 = Color3.new(0, 0, 0)
Button.BackgroundTransparency = 0.75
Button.BorderColor3 = Color3.new(1, 1, 1)
Button.Position = UDim2.new(0, 0, 0, 1)
Button.Size = UDim2.new(0, 117, 0, 18)
Button.AutoButtonColor = false
Button.Font = Enum.Font.SourceSans
Button.Text = ""
Button.TextColor3 = Color3.new(0, 0, 0)
Button.TextSize = 14
Button.Active = true

local RightPanel = Instance.new("Frame")
RightPanel.Name = "RightPanel"
RightPanel.Parent = Background
RightPanel.BackgroundColor3 = Color3.fromRGB(37, 36, 38)
RightPanel.BorderSizePixel = 0
RightPanel.Position = UDim2.new(0, 131, 0, 19)
RightPanel.Size = UDim2.new(0, 319, 0, 249)

local CodeBox = Instance.new("Frame")
CodeBox.Name = "CodeBox"
CodeBox.Parent = RightPanel
CodeBox.BackgroundColor3 = Color3.fromRGB(13, 12, 14)
CodeBox.BorderSizePixel = 0
CodeBox.Size = UDim2.new(0, 319, 0, 119)

local TextBox = Instance.new("TextBox")
TextBox.Name = "TextBox"
TextBox.Parent = CodeBox
TextBox.BackgroundTransparency = 1
TextBox.Size = UDim2.new(1, 0, 1, 0)
TextBox.Text = "-- Seleziona un remote per vedere lo script generato"
TextBox.TextColor3 = Color3.new(1, 1, 1)
TextBox.TextSize = 14
TextBox.Font = Enum.Font.Code
TextBox.TextXAlignment = Enum.TextXAlignment.Left
TextBox.TextYAlignment = Enum.TextYAlignment.Top
TextBox.TextWrapped = false
TextBox.ClearTextOnFocus = false
TextBox.MultiLine = true

-- Remote logging function
local function addRemote(type, name, args, remote, blocked)
	if blacklist[remote] or blacklist[name] then return end
	
	local remoteFrame = RemoteTemplate:Clone()
	remoteFrame.Text.Text = string.sub(name, 1, 50)
	remoteFrame.ColorBar.BackgroundColor3 = type == "event" and Color3.new(255, 242, 0) or Color3.fromRGB(99, 86, 245)
	remoteFrame.LayoutOrder = layoutOrderNum
	layoutOrderNum = layoutOrderNum - 1
	
	local log = {
		Name = name,
		Remote = remote,
		Args = args,
		Blocked = blocked,
		Log = remoteFrame,
		GenScript = blocked and "-- THIS REMOTE WAS BLOCKED\n\n" .. genScript(remote, args) or genScript(remote, args),
	}
	
	logs[#logs + 1] = log
	
	remoteFrame.Button.MouseButton1Click:Connect(function()
		if selected and selected.Log then
			TweenService:Create(selected.Log.Button, TweenInfo.new(0.3), {BackgroundColor3 = Color3.new(0, 0, 0)}):Play()
		end
		selected = log
		if selected.Log then
			TweenService:Create(selected.Log.Button, TweenInfo.new(0.3), {BackgroundColor3 = Color3.fromRGB(92, 126, 229)}):Play()
			TextBox.Text = selected.GenScript
		end
		if sideClosed then
			sideClosed = false
			TweenService:Create(RightPanel, TweenInfo.new(0.3), {Size = UDim2.new(0, 319, 0, 249)}):Play()
		end
	end)
	
	remoteFrame.Parent = LogList
	table.insert(remoteLogs, {remoteFrame})
	
	LogList.CanvasSize = UDim2.new(0, 0, 0, UIListLayout.AbsoluteContentSize.Y)
end

-- Hook setup with detour pattern (more reliable)
local originalNamecall

local function setupHooks()
	if not hookmetamethod or not getnamecallmethod then
		error("hookmetamethod/getnamecallmethod non disponibili! Questa funzione richiede un executor moderno (Synapse X, Krampus, etc.)")
	end
	
	originalNamecall = hookmetamethod(game, "__namecall", function(self, ...)
		local methodName = getnamecallmethod()
		local args = {...}
		
		if typeof(self) == "Instance" and (methodName == "FireServer" or methodName == "InvokeServer") then
			local name = self.Name
			
			-- Fire signal for API users
			if remoteSignals[self] then
				remoteSignals[self]:Fire(methodName, args)
			end
			
			-- Add to logs (non-blocking)
			coroutine.wrap(function()
				addRemote(methodName == "FireServer" and "event" or "function", name, args, self, blocklist[self] or blocklist[name])
			end)()
			
			-- Check blocklist - prevent firing
			if blocklist[self] or blocklist[name] then
				return nil
			end
			
			-- Check for hooks
			if remoteHooks[self] then
				local hookedArgs = remoteHooks[self](unpack(args))
				if hookedArgs then
					return originalNamecall(self, unpack(hookedArgs))
				end
			end
		end
		
		return originalNamecall(self, ...)
	end)
	
	return originalNamecall
end

-- SimpleSpy API
local SimpleSpy = {}

function SimpleSpy:GetRemoteFiredSignal(remote)
	assert(typeof(remote) == "Instance", "Instance expected, got " .. typeof(remote))
	if not remoteSignals[remote] then
		remoteSignals[remote] = newSignal()
	end
	return remoteSignals[remote]
end

function SimpleSpy:HookRemote(remote, callback)
	assert(typeof(remote) == "Instance", "Instance expected, got " .. typeof(remote))
	assert(typeof(callback) == "function", "function expected, got " .. typeof(callback))
	remoteHooks[remote] = callback
end

function SimpleSpy:BlockRemote(remote)
	assert(typeof(remote) == "Instance" or typeof(remote) == "string", "Instance | string expected, got " .. typeof(remote))
	blocklist[remote] = true
end

function SimpleSpy:ExcludeRemote(remote)
	assert(typeof(remote) == "Instance" or typeof(remote) == "string", "Instance | string expected, got " .. typeof(remote))
	blacklist[remote] = true
end

function SimpleSpy:ValueToString(value)
	return v2s(value)
end

function SimpleSpy:TableToVars(t)
	assert(typeof(t) == "table", "table expected, got " .. typeof(t))
	return v2s(t)
end

function SimpleSpy:ArgsToString(method, args)
	assert(typeof(method) == "string", "string expected, got " .. typeof(method))
	assert(typeof(args) == "table", "table expected, got " .. typeof(args))
	return v2s({args = args}) .. "\n\n" .. method .. "(unpack(args))"
end

-- Button connections
CloseButton.MouseButton1Click:Connect(function()
	if originalNamecall then
		hookmetamethod(game, "__namecall", originalNamecall)
	end
	_G.SimpleSpyShutdown = nil
	SimpleSpy2:Destroy()
end)

Simple.MouseButton1Click:Connect(function()
	sideClosed = not sideClosed
	if sideClosed then
		TweenService:Create(RightPanel, TweenInfo.new(0.3), {Size = UDim2.new(0, 0, 0, 249)}):Play()
	else
		TweenService:Create(RightPanel, TweenInfo.new(0.3), {Size = UDim2.new(0, 319, 0, 249)}):Play()
	end
end)

-- Initialize
if not RunService:IsClient() then
	error("SimpleSpy può essere eseguito solo dal client!")
end

local success, err = pcall(function()
	setupHooks()
end)

if not success then
	warn("SimpleSpy initialization error:", err)
else
	_G.SimpleSpyExecuted = true
	_G.SimpleSpyShutdown = function()
		if originalNamecall then
			hookmetamethod(game, "__namecall", originalNamecall)
		end
		_G.SimpleSpyExecuted = nil
		_G.SimpleSpyShutdown = nil
		SimpleSpy2:Destroy()
	end
	
	if gethui then
		SimpleSpy2.Parent = gethui()
	else
		SimpleSpy2.Parent = CoreGui
	end
	
	RemoteTemplate.Parent = nil
	
	print("SimpleSpy Modern inizializzato con successo!")
end

return SimpleSpy